// Auth Action Types
export const SET_LOGIN_USER_REQUEST = "SET_LOGIN_USER_REQUEST";
export const SET_LOGIN_USER_SUCCESS = "SET_LOGIN_USER_SUCCESS";
export const SET_LOGIN_USER_FAILURE = "SET_LOGIN_USER_FAILURE";

export const SET_REGISTER_USER_REQUEST = "SET_REGISTER_USER_REQUEST";
export const SET_REGISTER_USER_SUCCESS = "SET_REGISTER_USER_SUCCESS";
export const SET_REGISTER_USER_FAILURE = "SET_REGISTER_USER_FAILURE";

export const LOGOUT = "LOGOUT";

// User Profile Action Types
export const SET_USER_PROFILE_REQUEST = "SET_USER_PROFILE_REQUEST";
export const SET_USER_PROFILE_SUCCESS = "SET_USER_PROFILE_SUCCESS";
export const SET_USER_PROFILE_FAILURE = "SET_USER_PROFILE_FAILURE";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";

// Chat Statistics Action Types
export const GET_CHAT_STATISTICS_REQUEST = "GET_CHAT_STATISTICS_REQUEST";
export const GET_CHAT_STATISTICS_SUCCESS = "GET_CHAT_STATISTICS_SUCCESS";
export const GET_CHAT_STATISTICS_FAILURE = "GET_CHAT_STATISTICS_FAILURE";

// Export Chat Action Types
export const EXPORT_CHAT_REQUEST = "EXPORT_CHAT_REQUEST";
export const EXPORT_CHAT_SUCCESS = "EXPORT_CHAT_SUCCESS";
export const EXPORT_CHAT_FAILURE = "EXPORT_CHAT_FAILURE";

// Delete Conversation Action Types
export const DELETE_CONVERSATION_REQUEST = "DELETE_CONVERSATION_REQUEST";
export const DELETE_CONVERSATION_SUCCESS = "DELETE_CONVERSATION_SUCCESS";
export const DELETE_CONVERSATION_FAILURE = "DELETE_CONVERSATION_FAILURE";

// Online Status Action Types
export const GET_ONLINE_USERS_REQUEST = "GET_ONLINE_USERS_REQUEST";
export const GET_ONLINE_USERS_SUCCESS = "GET_ONLINE_USERS_SUCCESS";
export const GET_ONLINE_USERS_FAILURE = "GET_ONLINE_USERS_FAILURE";
export const SET_USER_ONLINE = "SET_USER_ONLINE";
export const SET_USER_OFFLINE = "SET_USER_OFFLINE";

// Add more action types below as needed
// e.g., SET_FORGOT_PASSWORD_REQUEST, etc.
